import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import { readFile, writeFile } from "node:fs/promises";
import { which } from "../util/which.js";
import { npmInstallGlobal } from "./npm-install.js";
import type { AgentAdapter, DetectResult, OpperRouting } from "./types.js";

const SENTINEL_OPEN = "# >>> opper-cli >>>";
const SENTINEL_CLOSE = "# <<< opper-cli <<<";
const PROVIDER = "opper-cli";

function codexConfigPath(): string {
  return join(process.env.CODEX_HOME || join(homedir(), ".codex"), "config.toml");
}

async function detect(): Promise<DetectResult> {
  if (!(await which("codex"))) return { installed: false };
  return { installed: true, configPath: codexConfigPath() };
}

async function install(): Promise<void> {
  await npmInstallGlobal("@openai/codex", "https://github.com/openai/codex");
}

async function isConfigured(): Promise<boolean> {
  // Routing is supplied to the launched process; no persistent setup is needed.
  return (await detect()).installed;
}

async function configure(): Promise<void> {
  // Current Codex profiles are separate files, not legacy [profiles.*] tables.
  // Invocation overrides work without changing the CLI or desktop's settings.
}

function isLegacyOpperBlock(block: string): boolean {
  // Refuse to remove manually added settings or malformed/nested markers, even
  // inside the old sentinel. Only the shape generated by this adapter is owned.
  let section: "provider" | "profile" | undefined;
  let hasProvider = false;
  let hasEnvironmentKey = false;
  for (const rawLine of block.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === SENTINEL_OPEN || line === SENTINEL_CLOSE) return false;
    if (!line || line.startsWith("#")) continue;
    if (line === "[model_providers.opper]") {
      if (hasProvider) return false;
      section = "provider";
      hasProvider = true;
    } else if (/^\[profiles\.opper-[a-z0-9-]+\]$/.test(line)) {
      section = "profile";
    } else if (section === "provider") {
      if (/^env_key\s*=\s*"OPPER_API_KEY"$/.test(line)) {
        hasEnvironmentKey = true;
      } else if (!/^(?:name\s*=\s*"Opper"|wire_api\s*=\s*"responses"|base_url\s*=\s*"[^"\r\n]+")$/.test(line)) {
        return false;
      }
    } else if (section !== "profile" || !/^(?:model\s*=\s*"[^"\r\n]+"|model_provider\s*=\s*"opper")$/.test(line)) {
      return false;
    }
  }
  return hasProvider && hasEnvironmentKey;
}

async function unconfigure(): Promise<void> {
  const cfg = codexConfigPath();
  let text: string;
  try {
    text = await readFile(cfg, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return;
    throw err;
  }
  const next = text.replace(
    /^# >>> opper-cli >>>\r?\n([\s\S]*?)^# <<< opper-cli <<<(?:\r?\n|$)/gm,
    (whole: string, body: string) => isLegacyOpperBlock(body) ? "" : whole,
  );
  if (next !== text) await writeFile(cfg, next, "utf8");
}

function hasNativeModelSelection(args: string[]): boolean {
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]!;
    if (arg === "--") break;
    if (/^(?:--(?:model|profile)(?:=|$)|-[mp])/.test(arg)) return true;
    // A native config override is also an explicit model choice.
    const config = arg === "-c" || arg === "--config"
      ? args[++i]
      : arg.startsWith("--config=") ? arg.slice(9)
      : arg.startsWith("-c") ? arg.slice(2) : undefined;
    if (config && /^model\s*=/.test(config)) return true;
  }
  return false;
}

async function spawn(args: string[], routing: OpperRouting): Promise<number> {
  // Keep the provider distinct from desktop and legacy `opper` configuration.
  // These flags affect only this invocation, so concurrent CLI/app launches
  // never overwrite each other's endpoint, selected model, or credentials.
  const provider = `{ name = "Opper", base_url = ${JSON.stringify(routing.baseUrl)}, env_key = "OPPER_API_KEY", wire_api = "responses", requires_openai_auth = false }`;
  const overrides = [
    "-c", `model_provider=${JSON.stringify(PROVIDER)}`,
    "-c", `model_providers.${PROVIDER}=${provider}`,
    // Codex defaults to a cached web-search tool that the gateway cannot serve.
    "-c", 'web_search="disabled"',
  ];
  const modelArgs = hasNativeModelSelection(args) ? [] : ["--model", routing.model];
  const result = spawnSync("codex", [...overrides, ...modelArgs, ...args], {
    stdio: "inherit",
    env: { ...process.env, OPPER_API_KEY: routing.apiKey },
  });
  return result.status ?? -1;
}

export const codex: AgentAdapter = {
  name: "codex",
  displayName: "Codex",
  docsUrl: "https://github.com/openai/codex",
  detect,
  isConfigured,
  configure,
  unconfigure,
  install,
  spawn,
};
